### ISSUE TITLE
/usr/local/bin/vagrant: No such file or directory

### ISSUE THREAD

**Issue by grtjn** [grtjn/mlvagrant#56]
Reported by @robpml:

```bash
$ vagrant plugin install vagrant-hostmanager
-bash: /usr/local/bin/vagrant: No such file or directory
```

Noticed when first installing Vagrant 1.7.4, uninstalling, and installing Vagrant 1.7.2.

**Comment by grtjn** [comment]
Vagrant 1.7.2 runs from /usr/bin/vagrant, and some plugins seem to depend on that hard-coded location. One could create a symlink with:

```
sudo ln -s /usr/bin/vagrant /usr/local/bin/vagrant
```

This page suggests it might be related with OSX updates, though not clear why:

http://pointlessramblings.com/posts/El_Capitan/

It does come with a slight alternate solution, which might be actually better than the above:

```
sudo ln -s /opt/vagrant/bin/vagrant /usr/local/bin/vagrant
```

**Comment by grtjn** [comment]
Closing it for the time being, likely difficult to reproduce. Written down above workaround for future reference..

**Comment by agoransson** [comment]
I had a very similar problem now that I reinstalled vagrant and virtualbox. The symlink didn't help, it turned out to be cached by bash.

[This stackexchange post](http://unix.stackexchange.com/questions/5609/how-do-i-clear-bashs-cache-of-paths-to-executables) helped me solve my problem.

Either clear the entire cache with `hash -r` or just one entry `hash -d vagrant`

**Comment by kasimir-k** [comment]
agoransson's cache clearing tip helped me:

I had upgraded VirtualBox to 5.0, after which Vagrant 1.6.5 complained that `version of VirtualBox installed that is not supported`. 

I upgraded Vagrant to 1.8.1 - then `vagrant up` resulted in `-bash: /usr/bin/vagrant: No such file or directory`

`hash -d vagrant` resolved this

**Comment by grtjn** [comment]
Thanks for reporting this!
